version: 2
jobs:
  build:
    docker:
      - image: node:alpine
    working_directory: ~/homeontheroute.com
    steps:
      - run:
          name: install AWS CLI
          command: |
            apk --no-cache update && \
            apk --no-cache add python py-pip && \
            pip --no-cache-dir install awscli
      - checkout
      - run:
          command: npm install
      - run:
          command: npm run install-typings
      - run:
          command: npm run build
      - run:
          name: Test compilation
          command: '[ -f ./built/app.bundle.js ]'
      - add_ssh_keys
      - deploy:
          command: ./bin/deploy-${CIRCLE_BRANCH}.sh
