version: 2
jobs:
  build:
    docker:
      - image: node:latest
    working_directory: ~/homeontheroute.com
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: npm run install-typings
      - run:
          command: npm run build
      - run:
          name: Test compilation
          command: '[ -f ./built/app.bundle.js ]'
      - add_ssh_keys
      - deploy:
          command: ./bin/deploy-${CIRCLE_BRANCH}.sh
